# fly.toml app configuration file generated for nfs-proto on 2025-09-18T01:16:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nfs-proto'
primary_region = 'syd'
# swap stops the suspend feature from working
# swap_size_mb = 2048

[build]
dockerfile = 'fly-nfs/Dockerfile'

[[services]]
internal_port = 2049
protocol = 'tcp'

[[services.ports]]
port = 2049

[[services.machine_checks]]
entrypoint = ["/bin/bash", "-lc"]
command = ["/self-mount-check.sh"]
timeout = "60s"
kill_signal = "SIGKILL"
kill_timeout = "5s"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[mounts]]
source = 'nfsdata'
destination = '/data'
