app = 'org1-openai-proxy'
primary_region = 'syd'

[build]
  dockerfile = 'fly-openai-proxy/Dockerfile'

[env]
  ALLOWED_ORIGINS = '*'
  OPENAI_API_BASE = 'https://api.openai.com'

[http_service]
  internal_port = 8080
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '15s'
    method = 'GET'
    path = '/healthz'
    protocol = 'http'
    timeout = '5s'

[[vm]]
  size = 'shared-cpu-1x'
