# fly.toml app configuration file generated for fly-auth on 2025-09-19T04:03:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-auth'
primary_region = 'syd'

[env]
FLY_ORG_SLUG = 'personal'
FLY_NFS_APP = 'nfs-proto'
FLY_AUTH_BASE_DOMAIN = 'agentic.dreamcatcher.land'
FLY_AGENT_TEMPLATE_APP = 'universal-compute'

CLERK_SIGN_UP_URL = 'https://accounts.agentic.dreamcatcher.land/sign-up'
CLERK_SIGN_IN_URL = 'https://accounts.agentic.dreamcatcher.land/sign-in'
CLERK_PUBLISHABLE_KEY = 'pk_live_Y2xlcmsuYWdlbnRpYy5kcmVhbWNhdGNoZXIubGFuZCQ'

DEBUG = '@artifact/fly-auth*'
DEBUG_HIDE_DATE = '1'
DEBUG_COLORS = '1'

[build]
dockerfile = 'fly-auth/Dockerfile'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 1


[[vm]]
size = 'shared-cpu-1x'
