# fly.toml app configuration file generated for org1-openai-proxy on 2025-09-29T06:04:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'org1-openai-proxy'
primary_region = 'syd'

[build]
dockerfile = 'fly-openai/Dockerfile'

[env]
ALLOWED_ORIGINS = '*'
OPENAI_API_BASE = 'https://api.openai.com'

[http_service]
internal_port = 8080
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0

[[vm]]
size = 'shared-cpu-1x'
