# fly.toml app configuration file generated for fly-computer on 2025-09-21T03:20:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-computer'
primary_region = 'syd'

[build]
dockerfile = 'fly-computer/Dockerfile'

[http_service]
internal_port = 8080
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0

[[vm]]
size = 'shared-cpu-1x'
