# fly.toml app configuration file generated for fly-computer on 2025-09-21T03:20:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-computer'
primary_region = 'syd'

[build]
dockerfile = 'fly-computer/Dockerfile'

[env]
FLY_NFS_APP = 'nfs-proto'
FLY_AUTH_BASE_DOMAIN = 'agentic.dreamcatcher.land'
FLY_AGENT_TEMPLATE_APP = 'universal-compute'

DEBUG = '@artifact/fly-computer*'
DEBUG_HIDE_DATE = '1'
DEBUG_COLORS = '1'

[http_service]
internal_port = 8080
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0

[[vm]]
size = 'shared-cpu-1x'

[[services]]
internal_port = 8080
protocol = 'tcp'
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
handlers = ["tls", "http"]
start_port = 3000
end_port = 30000
