# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'universal-compute'
primary_region = 'syd'

[build]
dockerfile = 'Dockerfile'

[env]
PORT = '8080'

[processes]
web = ''
worker = ''

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
processes = ['web']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
