# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'universal-compute'
primary_region = 'syd'

[build]
dockerfile = 'Dockerfile'

[env]
PORT = '8080'

[http_service]
port = 8080
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[services]]
start_port = 3000
end_port = 30000
[[services.ports]]
handlers = ["http"]
force_https = true
start_port = 3000
end_port = 30000
