app = 'org1-fly-exec'
primary_region = 'syd'

[build]
  dockerfile = 'fly-exec/Dockerfile'

[env]
  # the deploy token for the DC_WORKER_POOL_APP
  # DC_FLY_API_TOKEN = '#secrets#'
  DC_DOMAIN = 'agentic.dreamcatcher.land'
  DC_NFS = 'nfs-proto.flycast'
  DC_ROUTER = 'org1-fly-router.flycast'
  DC_EXEC = 'org1-fly-exec.flycast'
  DC_WORKER_POOL_APP = 'org1-worker-pool'

  DEBUG = '@artifact/fly-exec*'
  DEBUG_COLORS = '1'
  DEBUG_HIDE_DATE = '1'

[http_service]
  internal_port = 8080
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
