app = 'org1-fly-host-coder'
primary_region = 'syd'
swap_size_mb = 2048

[experimental]
  lazy_load_images = true

[build]
  dockerfile = 'hosts/coder.dockerfile'

[deploy]
  release_command = '/app/supervisor/release.ts host-coder'

[env]
  DC_DOMAIN = 'agentic.dreamcatcher.land'
  DC_EXEC = 'org1-fly-exec.flycast'
  DC_NFS = 'nfs-proto.flycast'
  DC_OPENAI_PROXY_BASE_URL = 'http://org1-openai-proxy.flycast'
  DC_ROUTER = 'org1-fly-router.flycast'
  DC_WORKER_POOL_APP = 'org1-worker-pool'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    start_port = 3000
    end_port = 30000
    handlers = ['tls', 'http']

# mcp supervisor service
[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 442
    handlers = ['tls', 'http']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
