# fly.toml app configuration file generated for fly-auth on 2025-09-19T04:03:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-auth'
primary_region = 'syd'

[build]
dockerfile = 'fly-auth/Dockerfile'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0

[[vm]]
size = 'shared-cpu-1x'
