# fly.toml app configuration file generated for org1-fly-exec on 2025-09-25T10:25:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'org1-fly-exec'
primary_region = 'syd'

[build]
  dockerfile = 'fly-exec/Dockerfile'

[env]
  DC_DOMAIN = 'agentic.dreamcatcher.land'
  DC_FLY_API_TOKEN = 'secrets'
  DC_NFS = 'nfs-proto.flycast'
  DEBUG = '@artifact/fly-exec*'
  DEBUG_COLORS = '1'
  DEBUG_HIDE_DATE = '1'

[http_service]
  internal_port = 8080
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
