app = 'universal-compute'
primary_region = 'syd'

[build]
dockerfile = 'RouterDockerfile'

# Default port your app listens on. Adjust if your server uses a different port.
[env]
PORT = "8080"

[processes]
web = ""

[http_service]
processes = ["web"]
internal_port = 8080
force_https = true
auto_start_machines = true
auto_stop_machines = "suspend"
min_machines_running = 0

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
