model                  = "gpt-5"
model_provider         = "openai"
model_reasoning_effort = "low"
model_verbosity        = "low"
approval_policy        = "never"
sandbox_mode           = "danger-full-access"

experimental_use_rmcp_client = true

notify = "__CODEX_NOTIFY__"

[model_providers.openai]
  name     = "OpenAI"
  base_url = "__OPENAI_PROXY_BASE_URL__"
  wire_api = "responses"

[tools]
  web_search = true
  view_image = true

[mcp_servers.dreamcatcher]
  url                  = "__MCP_DREAMCATCHER_URL__"
  bearer_token_env_var = "__MCP_DREAMCATCHER_BEARER_TOKEN_ENV_VAR__"
